name: welcome

on: [workflow_dispatch]

jobs:
  hello:
    runs-on: ubuntu-latest
    name: howdy
    steps:
    - uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
